import type { editor } from 'monaco-editor';

export const VITESSE_DARK_THEME = 'vitesse-dark';
export const VITESSE_LIGHT_THEME = 'vitesse-light';

export const VITESSE_DARK_MONACO_THEME: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  colors: {
    'editor.background': '#121212',
    'editor.foreground': '#dbd7caee',
    'editor.lineHighlightBackground': '#181818',
    'editor.selectionBackground': '#eeeeee18',
    'editor.selectionHighlightBackground': '#eeeeee10',
    'editor.inactiveSelectionBackground': '#eeeeee10',
    'editor.findMatchBackground': '#e6cc7722',
    'editor.findMatchHighlightBackground': '#e6cc7744',
    'editor.wordHighlightBackground': '#1c6b4805',
    'editor.wordHighlightStrongBackground': '#1c6b4810',
    'editorCursor.foreground': '#dbd7caee',
    'editorLineNumber.foreground': '#dedcd550',
    'editorLineNumber.activeForeground': '#bfbaaa',
    'editorGutter.background': '#121212',
    'editorIndentGuide.background': '#ffffff15',
    'editorIndentGuide.activeBackground': '#ffffff30',
    'editorWhitespace.foreground': '#ffffff15',
    'editorError.foreground': '#cb7676',
    'editorWarning.foreground': '#d4976c',
    'editorInfo.foreground': '#6394bf',
    'editorHint.foreground': '#4d9375',
    'editorWidget.background': '#121212',
    'editorWidget.foreground': '#dbd7caee',
    'editorHoverWidget.background': '#181818',
    'editorHoverWidget.foreground': '#dbd7caee',
    'editorHoverWidget.border': '#191919',
    'editorSuggestWidget.background': '#121212',
    'editorSuggestWidget.foreground': '#dbd7caee',
    'editorSuggestWidget.selectedBackground': '#181818',
    'editorSuggestWidget.highlightForeground': '#4d9375',
    'editorBracketMatch.background': '#4d937520',
    'editorBracketHighlight.foreground1': '#5eaab5',
    'editorBracketHighlight.foreground2': '#4d9375',
    'editorBracketHighlight.foreground3': '#d4976c',
    'editorBracketHighlight.foreground4': '#d9739f',
    'editorBracketHighlight.foreground5': '#e6cc77',
    'editorBracketHighlight.foreground6': '#6394bf',
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.background': '#dedcd510',
    'scrollbarSlider.hoverBackground': '#dedcd550',
    'scrollbarSlider.activeBackground': '#dedcd550',
  },
  rules: [
    { token: '', foreground: 'dbd7ca' },
    { token: 'comment', foreground: '758575', fontStyle: 'italic' },
    { token: 'comment.block.json', foreground: '758575', fontStyle: 'italic' },
    { token: 'comment.line.json', foreground: '758575', fontStyle: 'italic' },
    { token: 'delimiter.bracket.json', foreground: '666666' },
    { token: 'delimiter.array.json', foreground: '666666' },
    { token: 'delimiter.colon.json', foreground: '666666' },
    { token: 'delimiter.comma.json', foreground: '666666' },
    { token: 'keyword.json', foreground: '4d9375' },
    { token: 'number.json', foreground: '4C9A91' },
    { token: 'string.key.json', foreground: 'b8a965' },
    { token: 'string.value.json', foreground: 'c98a7d' },
    { token: 'string', foreground: 'c98a7d' },
    { token: 'number', foreground: '4C9A91' },
    { token: 'keyword', foreground: '4d9375' },
  ],
};

export const VITESSE_LIGHT_MONACO_THEME: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  colors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#393a34',
    'editor.lineHighlightBackground': '#f7f7f7',
    'editor.selectionBackground': '#22222218',
    'editor.selectionHighlightBackground': '#22222210',
    'editor.inactiveSelectionBackground': '#22222210',
    'editor.findMatchBackground': '#e6cc7744',
    'editor.findMatchHighlightBackground': '#e6cc7766',
    'editor.wordHighlightBackground': '#1c6b4805',
    'editor.wordHighlightStrongBackground': '#1c6b4810',
    'editorCursor.foreground': '#393a34',
    'editorLineNumber.foreground': '#393a3450',
    'editorLineNumber.activeForeground': '#4e4f47',
    'editorGutter.background': '#ffffff',
    'editorIndentGuide.background': '#00000015',
    'editorIndentGuide.activeBackground': '#00000030',
    'editorWhitespace.foreground': '#00000015',
    'editorError.foreground': '#ab5959',
    'editorWarning.foreground': '#a65e2b',
    'editorInfo.foreground': '#296aa3',
    'editorHint.foreground': '#1e754f',
    'editorWidget.background': '#ffffff',
    'editorWidget.foreground': '#393a34',
    'editorHoverWidget.background': '#f7f7f7',
    'editorHoverWidget.foreground': '#393a34',
    'editorHoverWidget.border': '#f0f0f0',
    'editorSuggestWidget.background': '#ffffff',
    'editorSuggestWidget.foreground': '#393a34',
    'editorSuggestWidget.selectedBackground': '#f7f7f7',
    'editorSuggestWidget.highlightForeground': '#1c6b48',
    'editorBracketMatch.background': '#1c6b4820',
    'editorBracketHighlight.foreground1': '#2993a3',
    'editorBracketHighlight.foreground2': '#1e754f',
    'editorBracketHighlight.foreground3': '#a65e2b',
    'editorBracketHighlight.foreground4': '#a13865',
    'editorBracketHighlight.foreground5': '#bda437',
    'editorBracketHighlight.foreground6': '#296aa3',
    'scrollbar.shadow': '#6a737d33',
    'scrollbarSlider.background': '#393a3410',
    'scrollbarSlider.hoverBackground': '#393a3450',
    'scrollbarSlider.activeBackground': '#393a3450',
  },
  rules: [
    { token: '', foreground: '393a34' },
    { token: 'comment', foreground: 'a0ada0', fontStyle: 'italic' },
    { token: 'comment.block.json', foreground: 'a0ada0', fontStyle: 'italic' },
    { token: 'comment.line.json', foreground: 'a0ada0', fontStyle: 'italic' },
    { token: 'delimiter.bracket.json', foreground: '999999' },
    { token: 'delimiter.array.json', foreground: '999999' },
    { token: 'delimiter.colon.json', foreground: '999999' },
    { token: 'delimiter.comma.json', foreground: '999999' },
    { token: 'keyword.json', foreground: '1e754f' },
    { token: 'number.json', foreground: '2f798a' },
    { token: 'string.key.json', foreground: '998418' },
    { token: 'string.value.json', foreground: 'b56959' },
    { token: 'string', foreground: 'b56959' },
    { token: 'number', foreground: '2f798a' },
    { token: 'keyword', foreground: '1e754f' },
  ],
};

export const DEFAULT_JSON = `{
  "name": "JSON Formatter",
  "version": "${__BUILD_VERSION__}",
  "description": "A beautiful JSON formatting tool",
  "author": "const",
  "site": "https://json.const.site",
  "blog": "https://blog.luckfunc.com",
  "updateTime": "${__BUILD_TIME__}",
  "features": [
    "format",
    "minify",
    "validate",
    "copy",
    "download",
    "live-validation"
  ],
  "config": {
    "theme": "auto",
    "autoFormat": false,
    "lineNumbers": true
  },
  "meta": {
    "created": "2025",
    "license": "MIT",
    "repository": "https://github.com/luckfunc/json-formatter"
  }
}`;
